name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@latest
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # укажите версию Node.js, если это необходимо

      - name: Install dependencies and start application
        run: |
          ssh -o StrictHostKeyChecking=no snusp@158.160.91.107 'cd /back_lab3 && npm install && npm run dev'
